-- CreateTable
CREATE TABLE "StoreInfo" (
    "id" TEXT NOT NULL DEFAULT 'singleton',
    "storeName" TEXT NOT NULL DEFAULT 'Medisuite',
    "tagline" TEXT NOT NULL DEFAULT 'Pharmacy essentials and skincare you can trust.',
    "description" TEXT NOT NULL DEFAULT 'COD delivery with ring-road pricing and clear return rules for eligible products.',
    "phone" TEXT NOT NULL DEFAULT '+977 9860802178',
    "email" TEXT NOT NULL DEFAULT 'support@medisuite.com',
    "address" TEXT NOT NULL DEFAULT 'Kathmandu, Nepal',
    "openingHours" TEXT NOT NULL DEFAULT '9:00 AM – 7:00 PM',
    "openDays" TEXT NOT NULL DEFAULT 'Sunday – Friday',
    "instagramUrl" TEXT NOT NULL DEFAULT '',
    "facebookUrl" TEXT NOT NULL DEFAULT '',
    "twitterUrl" TEXT NOT NULL DEFAULT '',
    "tiktokUrl" TEXT NOT NULL DEFAULT '',
    "newsletterEnabled" BOOLEAN NOT NULL DEFAULT true,
    "newsletterText" TEXT NOT NULL DEFAULT 'Get offers + skincare tips',
    "termsUrl" TEXT NOT NULL DEFAULT '/pages/terms',
    "privacyUrl" TEXT NOT NULL DEFAULT '/pages/privacy',
    "refundUrl" TEXT NOT NULL DEFAULT '/pages/refund',
    "aboutHeadline" TEXT NOT NULL DEFAULT 'About Us',
    "aboutSubheadline" TEXT NOT NULL DEFAULT 'We are a modern pharmacy and skincare store.',
    "aboutBody" TEXT NOT NULL DEFAULT 'Focused on quality, safety, and everyday wellness. We deliver genuine products with COD across Kathmandu.',
    "aboutMission" TEXT NOT NULL DEFAULT 'To make quality healthcare accessible for every family.',
    "aboutVision" TEXT NOT NULL DEFAULT 'Nepal''s most trusted online pharmacy.',
    "stat1Val" TEXT NOT NULL DEFAULT '100%',
    "stat1Label" TEXT NOT NULL DEFAULT 'Genuine Products',
    "stat2Val" TEXT NOT NULL DEFAULT '2000+',
    "stat2Label" TEXT NOT NULL DEFAULT 'Happy Customers',
    "stat3Val" TEXT NOT NULL DEFAULT 'Same Day',
    "stat3Label" TEXT NOT NULL DEFAULT 'Delivery',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "StoreInfo_pkey" PRIMARY KEY ("id")
);
